### PR TITLE
Add NAT Support

### PR DESCRIPTION
**Pull request by aaronsace**

### CODE REVIEW

**Comment by freshstudio** [comment]
Will it make a new mapping if I change listening port in MonoTorrent?

**Comment by aaronsace** [comment]
Yes, it's linked to the listener base class.

**Comment by yunchiri** [comment]
I changed original source to your source

alway exception 

MonoTorrent.Nat.MappingException: 'Error 718: ConflictInMappingEntry'

what can i do? i first time meet upnp , help me

**Comment by aaronsace** [comment]
I'm not expert on this but I think that's a standard error code from your router. Check there isn't any 'conflicts' on your router? 

Error code 718 is in the spec: http://upnp.org/specs/gw/UPnP-gw-WANIPConnection-v1-Service.pdf

**Comment by yunchiri** [comment]
@aaronsace Thanks feedback
NatManager.cs -> CloseNatDevice has error when release udp port

UdpListener.cs
Stop() ->

`            try
            {
                client.Close();
            }
            catch
            {

            }`

to

`            RaiseStatusChanged(ListenerStatus.NotListening);
            try
            {
                client.Close();
            }
            catch
            {

            }`

**Comment by yunchiri** [comment]
And 
Application Error When Non-NAT envoriments

**Comment by yunchiri** [comment]
I changed code for avoid NatDeviceNotFoundException

```
        private static async Task< NatDevice > FindNatDevice()
        {
            if (NatDevice != null) return NatDevice;

            NatDevice natDevice = null;
            try
            {
                natDevice = await (new NatDiscoverer()).DiscoverDeviceAsync(); //(PortMapper.Upnp, (new System.Threading.CancellationTokenSource(10000)));
                NatDevice = natDevice;
            }
            catch (NatDeviceNotFoundException ex)
            {
                Trace.WriteLine("Unable to find NAT device: " + ex);
                throw new NatDeviceNotFoundException();
            }
            catch (Exception ex)
            {
                Trace.WriteLine("NAT failed: " + ex);
            }
            return natDevice;
        }
```

```
        private static async void OpenNatDevice(ProtocolType protocol, int port)
        {
            try
            {
                NatDevice natDevice = await FindNatDevice();

                switch (protocol)
                {
                    case ProtocolType.Tcp:
                        //await NatDevice.CreatePortMapAsync(new Mapping(MonoTorrent.Nat.Protocol.Tcp, port, port, (int)Timer.Interval / 1000 * 2, "MonoTorrent"));
                        await natDevice.CreatePortMapAsync(new Mapping(MonoTorrent.Nat.Protocol.Tcp, port, port, "MonoTorrent"));
                        break;
                    case ProtocolType.Udp:
                        //await NatDevice.CreatePortMapAsync(new Mapping(MonoTorrent.Nat.Protocol.Udp, port, port, (int)Timer.Interval / 1000 * 2, "MonoTorrent"));
                        await natDevice.CreatePortMapAsync(new Mapping(MonoTorrent.Nat.Protocol.Udp, port, port, "MonoTorrent"));
                        break;
                }

            }
            catch(NatDeviceNotFoundException ex)
            {
                Trace.WriteLine("No NAT envoriment: " + ex);
            }
            catch (MappingException ex)
            {
                Trace.WriteLine("Unable to open NAT device: " + ex);
            }
            catch (Exception ex)
            {
                Trace.WriteLine("NAT failed: " + ex);
            }
        }
```

```
        private static async void CloseNatDevice(ProtocolType protocol, int port)
        {
            try
            {
                NatDevice natDevice = await FindNatDevice();

                switch (protocol)
                {
                    case ProtocolType.Tcp:
                        //await NatDevice.DeletePortMapAsync(new Mapping(MonoTorrent.Nat.Protocol.Tcp, port, port, (int)Timer.Interval / 1000 * 2, "MonoTorrent"));
                        await NatDevice.DeletePortMapAsync(new Mapping(MonoTorrent.Nat.Protocol.Tcp, port, port, "Mono Torrent"));
                        break;
                    case ProtocolType.Udp:
                        //await NatDevice.DeletePortMapAsync(new Mapping(MonoTorrent.Nat.Protocol.Udp, port, port, (int)Timer.Interval / 1000 * 2, "MonoTorrent"));
                        await NatDevice.DeletePortMapAsync(new Mapping(MonoTorrent.Nat.Protocol.Udp, port, port, "Mono Torrent"));
                        break;
                }
            }
            catch (NatDeviceNotFoundException ex)
            {
                Trace.WriteLine("No NAT envoriment: " + ex);
            }
            catch (MappingException ex)
            {
                Trace.WriteLine("Unable to close NAT device: " + ex);
            }
            catch (Exception ex)
            {
                Trace.WriteLine("NAT failed: " + ex);
            }
        }
```

**Comment by aaronsace** [comment]
@yunchiri Did you add an include for 'Task'?

**Comment by yunchiri** [comment]
@aaronsace 

using System.Threading.Tasks; <--

I didn't test well
but program running on NAT, none-NAT 

Thanks your job

**Comment by aaronsace** [comment]
@yunchiri Why have you removed the 'lifetime' as you risk leaving it open for longer than required?

**Comment by yunchiri** [comment]
@aaronsace  
=================
app launch => open port
app close => close port

so I don't need lifetime now
it's only my case :)

**Comment by aaronsace** [comment]
The lifetime was never needed but it relies on the app closing gracefully. Please can you add it back and lets work out the problems that you were having?

**Comment by yunchiri** [comment]
problem is 
"**Conflict with an already existing mapping**"(718) exception 
but it has no problem to running app

**Comment by aaronsace** [comment]
@yunchiri 1a3d9237edc64908da25615843e8607941fb3e9a

**Comment by masterwok** [comment]
I'm experiencing multiple build errors when merging this into a fresh clone. It appears that the csproj is missing from MonoTorrent.Nat?

**Comment by aaronsace** [comment]
@masterwok 'csproj' files are Visual Studio files. I don't have Visial Studio installed but I am quite sure just open the the source files on Visual Studio and a csproj is created for you.

**Comment by masterwok** [comment]
@aaronsace Thank you for the quick response. I don't think MonoTorrent.Nat can be added to the solution without a csproj file. I've tried both Rider and Visual Studio. I'm going to try and fix the broken references. I'll create a pull request once I figure it out.

It looks like you've done quite a bit of development on this project in your fork. How do you feel about the state of this project/your fork? Are there any major limitations of this project or missing features? I'm trying to determine why this project seems to not be very active and whether or not I should bring it into an application I'm considering building. Thank you!

**Comment by aaronsace** [comment]
@masterwok It works but it is not as good as utorrent; what is though. Just wish the owner would be more active as they are killing it like many GitHub projects. With it being fully C#, it should run on Windows, Linux, Mac, iOS, Android, PowerShell 6; add a cross platform interface and it's complete. 

Regarding the circular dependency, I don't run it separate; I presume moving NatManager.cs from MonoTorrent.Nat to MonoTorrent.Common would remove that issue...?

MonoTorrent fully merged here: https://github.com/MultiPoolMiner/monotorrent

MonoTorrent is integrated into here: https://github.com/MultiPoolMiner/MultiPoolMiner

**Comment by masterwok** [comment]
@aaronsace I see, thank you. It would probably work to bring that class into the Common project. I think I need to do more research into the actual protocol itself, but one day I hope bring this library or something similar into a cross-platform Xamarin application.

**Comment by alanmcgovern** [comment]
If you want to use Mono.Nat then just use Mono.Nat by referencing the library in your project. It doesn't need to be integrated into monotorrent directly.

**Pull request closed without merging**
