### PR TITLE
Fix magnet stuck on metadata when resuming

### PR DESCRIPTION
**Pull request by aaronsace**

### CODE REVIEW

**Comment by alanmcgovern** [comment]
What's the bug you were addressing?

**Comment by aaronsace** [comment]
If I remember correctly. When you load a magnet that you had previously started downloading then the torrent file being there was causing problems. This loads the torrent file if it is there already.

**Comment by alanmcgovern** [comment]
Thanks - test added and bug fixed!

**Comment by alanmcgovern** [comment]
Actually what i should've done was add the changes to this PR and merge this one :p

**Comment by alanmcgovern** [comment]
Now it's done :p

**Pull request closed without merging**
